### ISSUE TITLE
Other Checkpoint

### ISSUE THREAD

**Issue by ardha27** [deroberon/demofusion-comfyui#3]
if i want to try this model, how i can write it?
https://huggingface.co/Lykon/DreamShaper/blob/main/DreamShaperXL1.0Alpha2_fixedVae_half_00001_.safetensors

**Comment by deroberon** [comment]
I've tried this one here. For any SDXL model in Huggingface, the correct form would be something like: "Lykon/DreamShaper". But the problem is that this is just an SDXL file inside an SD1.5 model. If you use the diffusers Huggingface python library to get the model (that is what this implementation uses), Huggingface returns an SD1.5 model that is not compatible with the SDXLPipeline that this implementations uses. 

There are some coding solutions to this: 1-) Coding a solution to use single file safetensors as model inputs. 2-) Turn the node more flexible and able to use any compatible Comfyui model loaded model, that is a little bit more complicated and will take a little bit more time but it seems to us to be the correct way to go.

But meanwhile.... I believe I will try to code the first one, and let you know when you could use this model.

**Comment by deroberon** [comment]
Good news. I've created a new type of node: "Demofusion From Single File". All you have to do is put the exact link you post here in the file name field. (In fact, it's already there because I use it for testing)

Then you should get something like this: 
![example2](https://github.com/deroberon/demofusion-comfyui/assets/171700/2dc5cf1b-d0bf-47cc-b09c-01e8b6c6d989)

**Comment by deroberon** [comment]
Probally I will transform the text field in a selector for local checkpoints in the next version, as the other Comfyui nodes. I believe it will be more practical.

**Comment by ardha27** [comment]
Nice work, thank you very much

**Comment by deroberon** [comment]
Anytime :)
I just made the change that allows you to select a checkpoint from your comfyui checkpoints.

**Comment by ardha27** [comment]
Wow cool, thanks
